# Generated by Django 2.1.7 on 2019-04-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_artige_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(choices=[(0, 'artige'), (1, 'instagram'), (2, 'telegram'), (3, 'facebook')], max_length=10, verbose_name='endpoint')),
                ('insta_user', models.CharField(max_length=100, verbose_name='Instagram Username')),
                ('insta_id', models.IntegerField(verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='artige_id',
        ),
    ]
