# Generated by Django 2.1.7 on 2019-04-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190405_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default=1, max_length=255, verbose_name='description about User'),
            preserve_default=False,
        ),
    ]
