# Generated by Django 2.1.7 on 2019-04-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190409_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
    ]
